version: "2"


services:
  shiny-server:
    build: .
    image: "lottokickers/shiny-server:v1"
    container_name: "shiny-server"
    hostname: "shiny-server"
    environment:
      - SERVICE_NAME=shiny-server
    volumes:
      - ./myapp:/srv/shiny-server
    expose:
      - "80"
    ports:
      - "8082:80"
